version: '3'

services:
  backend:
    build: ./backend
    command: ['uvicorn', 'src.main:app', '--reload', '--host', '0.0.0.0', '--port', '8000']
    env_file:
      - ./.env/.backend.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/backend/src

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/frontend/src

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./.env/.db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
